kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mrdevops                    
  type: LoadBalancer                   
